### ISSUE TITLE
bosh.io publication

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry-community/node-exporter-boshrelease#1]
Nice to have a dedicated release for prometheus node exporter.
This will ease the runtime-config deployment with less coupling with the fast moving prometheus-bosh-release.
I cant find node-exporter-boshrelease on bosh.io, shall we ask Dmitry ?
kind regards
Pierre

**Comment by frodenas** [comment]
Please, do it. I already asked to be included in bosh.io 2 weeks ago.

**Comment by cppforlife** [comment]
Related: https://github.com/cloudfoundry-community/node-exporter-boshrelease/pull/2

**Comment by jmcarp** [comment]
@cppforlife: any progress on this?

**Comment by frodenas** [comment]
The request has been made, so I'm going to close this issue, it doesn't make sense to keep it open.

In the meantime, I suggest using the tarball included at the [releases](https://github.com/cloudfoundry-community/node-exporter-boshrelease/releases) section of this github repo. If you are using concourse, you can use the [github-release-resource](https://github.com/concourse/github-release-resource) to check/download the tarball.

**Comment by geofffranks** [comment]
If you need the sha1/URL links in a programatic fashion, you can also grab them from the Genesis Index - `curl genesis.starkandwayne.com/v1/release/node-exporter` (to filter for versions,  add`/latest`  to the end of the URL for latest, or `/v/<version-number>` for the version)
