### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by Houlistonm** [cloudfoundry-community/node-exporter-boshrelease#10]
node_exporter is currently at 1.5.x
Any plans to update?
Would you be receptive to a PR?

**Comment by benjaminguttmann-avtq** [comment]
Hi @Houlistonm , thank you for your issue.

We are currently working on getting everything up to date again in here. 
I just prepared a PR to bump node_exporter.

**Comment by benjaminguttmann-avtq** [comment]
We just released [v5.1.0](https://github.com/bosh-prometheus/node-exporter-boshrelease/releases/tag/v5.1.0) feel free to let us know if you face any issues.
