### ISSUE TITLE
Please add support for the ethtool exporter

### ISSUE THREAD

**Issue by Houlistonm** [cloudfoundry-community/node-exporter-boshrelease#12]
Please add support for the ethtool collector.

The additional AWS specific metrics returned via ethtool are invaluable to our team.

[issue](https://github.com/prometheus/node_exporter/pull/1832) that added ethtool support to node-exporter.

Specifically the metrics discussed [here](https://github.com/prometheus/node_exporter/issues/1908#issuecomment-891437168)

Note that the Jammy stemcells include ethtool.

**Comment by benjaminguttmann-avtq** [comment]
@Houlistonm release https://github.com/bosh-prometheus/node-exporter-boshrelease/releases/tag/v5.2.0 should fix this issue
