### ISSUE TITLE
addon does not work on Windows Cells

### ISSUE THREAD

**Issue by kkellner** [cloudfoundry-community/node-exporter-boshrelease#3]
When using addon in an environment that has "Runtime for Windows" tile (for Windows2012R2 stack), BOSH fails with error:

```
Started updating instance windows_diego_cell > windows_diego_cell/e156529e-a5ba-48be-a9a2-0632b8f302c7 (0) (canary). Failed: Action Failed start: Configuring jobs: Configuring job node_exporter: Adding monit configuration: invalid character 'c' looking for beginning of value (00:00:29)

Error 450001: Action Failed start: Configuring jobs: Configuring job node_exporter: Adding monit configuration: invalid character 'c' looking for beginning of value
```

Must include the following in the `runtime-config` so it's excluded from the windows stemcells:

```
 include:
     stemcell: 
     - os: ubuntu-trusty
```

Would be nice if Windows stemcell stats were also captured.  At a minimum the above "include" workaround should be documented in the readme.

**Comment by frodenas** [comment]
Good catch @kkellner, thanks for reporting it. I've added some notes at the README.

This is going to be a common topic, even the [common addons](https://bosh.io/docs/addons-common.html) don't seem to take this into account.
