### ISSUE TITLE
how to remove node-exporter from runtime config

### ISSUE THREAD

**Issue by mitulsheth** [cloudfoundry-community/node-exporter-boshrelease#4]
Trying to remove prometheus and node-exporter using bosh. I was successful in removing prometheus however not sure how to remove node-exporter and make necessary changes in runtime config we initially made while adding  node-exporter

**Comment by frodenas** [comment]
Create a runtime-config file with:

```
releases: []
addons: []
```

And run `bosh update runtime-config <filename>`.

**Comment by mitulsheth** [comment]
It worked !!! Yay !!!! Thanks @frodenas
