### ISSUE TITLE
The address should be provided via bosh links

### ISSUE THREAD

**Issue by johannaratliff** [cloudfoundry-community/node-exporter-boshrelease#7]
As a fellow bosh release developer, I would find it helpful to have the node-exporter's address available via bosh [link](https://bosh.io/docs/links/).

/cc @apoydence

**Comment by frodenas** [comment]
@johannasmith what's the use case for adding a link? This bosh-release is typically deployed as an add-on, so a link will not help here. Are there any other use cases you have in mind?

**Comment by johannaratliff** [comment]
We currently have to hard code the addr. I believe we ran into this same issue when we wanted a bosh link on an agent. You definitely need a independent place outside the add-on, which it doesn't look like is an option for the node-exporter.
